# The image used to build the Dremio cluster. It is recommended to update the
# version tag to the version that you are using. This will ensure that all
# the pods are using the same version of the software.
image: jonnydixon/hive-external-metastore
imageTag: 1.3
imagePullSecrets: dockerlogin

# Check out Dremio documentation for memory and cpu requirements for
# the coordinators and the executors.
# The value of memory should be in MB. CPU is in no of cores.
hive:
  port: 9083
