{{ if not .Values.DremioAdmin }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-master
spec:
  serviceName: "dremio-cluster-pod"
  replicas: 1
  selector:
    matchLabels:
      app: dremio-coordinator
  template:
    metadata:
      labels:
        app: dremio-coordinator
        role: dremio-cluster-pod
      annotations:
        dremio-configmap/checksum: {{ (.Files.Glob "config/*").AsConfig | sha256sum }}
        {{- if .Values.hive2 }}
        hive2-configmap/checksum: {{ (.Files.Glob "hive-2-conf/*").AsConfig | sha256sum }}
        {{- end }}
        {{- if .Values.hive3 }}
        hive3-configmap/checksum: {{ (.Files.Glob "hive-3-conf/*").AsConfig | sha256sum }}
        {{- end }}
    spec:
      affinity:
        {{- if .Values.coordinator.specifyAgentPool }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - {{.Values.coordinator.agentpool.name}}
        {{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - dremio-master
              topologyKey: "kubernetes.io/hostname"
        {{- end }}
      terminationGracePeriodSeconds: 5
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      containers:
      - name: dremio-master-coordinator
        image: {{.Values.image}}:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: {{.Values.coordinator.memory}}M
            cpu: {{.Values.coordinator.cpu}}
        volumeMounts:
        - name: dremio-master-log
          mountPath: /opt/dremio/log
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        - name: dremio-config
          mountPath: /opt/dremio/conf
        {{- if or .Values.tls.ui.enabled .Values.tls.client.enabled }}
        - name: dremio-tls
          mountPath: /opt/dremio/tls
        {{- end }}
        {{- if .Values.hive2 }}
        - name: dremio-hive2-config
          mountPath: /opt/dremio/plugins/connectors/hive2.d
        {{- end }}
        {{- if .Values.hive3 }}
        - name: dremio-hive3-config
          mountPath: /opt/dremio/plugins/connectors/hive3.d
        {{- end }}
        env:
        - name: DREMIO_LOG_TO_CONSOLE
          value: "0"
        - name: DREMIO_LOG_DIR
          value: /opt/dremio/log
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "{{ template "HeapMemory" .Values.coordinator.memory }}"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "{{ template "DirectMemory" .Values.coordinator.memory }}"
        - name: DREMIO_JAVA_EXTRA_OPTS
          value: >-
            -Dzookeeper=zk-hs:2181
            -Dservices.coordinator.master.embedded-zookeeper.enabled=false
            -Dservices.executor.enabled=false
            {{- if .Values.extraStartParams }}
            {{ .Values.extraStartParams }}
            {{- end }}
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: >-
            -XX:+UseG1GC
            -XX:G1HeapRegionSize=32M
            -XX:MaxGCPauseMillis=500
            -XX:InitiatingHeapOccupancyPercent=25
        - name: DREMIO_STOP_TIMEOUT
          value: "86400"
        command: ["/opt/dremio/bin/dremio"]
        args:
        - "start-fg"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
        - containerPort: 12543
          name: prometheus
        readinessProbe:
          httpGet:
            path: /
            {{- if .Values.tls.ui.enabled }}
            scheme: HTTPS
            {{- end }}
            port: 9047
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: json-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/json/server.json"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: query-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/queries.json"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: metadata-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/metadata_refresh.log"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: access-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/access.log"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: serverout-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/server.out"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: serverlog-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/server.log"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      - name: hivedeprecation-logs
        image: busybox
        args: ["sh", "-c", "sh /home/user/log-to-console.sh /opt/dremio/log/hive.deprecated.function.warning.log"]
        volumeMounts:
          - name: log-script
            mountPath: /home/user
          - name: dremio-master-log
            mountPath: /opt/dremio/log
      initContainers:
      - name: start-only-one-master
        image: busybox
        command: ["sh", "-c", "INDEX=${HOSTNAME##*-}; if [ $INDEX -ne 0 ]; then echo Only one master should be running.; exit 1; fi; "]
      - name: wait-for-zk
        image: busybox
        command:  ["sh", "-c", "until ping -c 1 -W 1 zk-hs > /dev/null; do echo waiting for zookeeper host; sleep 2; done;"]
      # since we're mounting a separate volume, reset permission to dremio uid/gid
      - name: chown-data-directory
        image: {{.Values.image}}:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["chown"]
        args:
        - "dremio:dremio"
        - "/opt/dremio/data"
      - name: upgrade-task
        image: {{.Values.image}}:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dremio-master-volume
          mountPath: /opt/dremio/data
        command: ["/opt/dremio/bin/dremio-admin"]
        args:
        - "upgrade"
      {{- if .Values.tls.ui.enabled }}
      - name: generate-ui-keystore
        image: {{.Values.image}}:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dremio-tls
          mountPath: /opt/dremio/tls
        - name: dremio-tls-secret-ui
          mountPath: /dremio-tls-secret
        command: ["/usr/bin/openssl"]
        args:
        - "pkcs12"
        - "-export"
        - "-inkey"
        - "/dremio-tls-secret/tls.key"
        - "-in"
        - "/dremio-tls-secret/tls.crt"
        - "-out"
        - "/opt/dremio/tls/ui.pkcs12"
        - "-passout"
        - "pass:"
      {{- end }}
      {{- if .Values.tls.client.enabled }}
      - name: generate-client-keystore
        image: {{.Values.image}}:{{.Values.imageTag}}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dremio-tls
          mountPath: /opt/dremio/tls
        - name: dremio-tls-secret-client
          mountPath: /dremio-tls-secret
        command: ["/usr/bin/openssl"]
        args:
        - "pkcs12"
        - "-export"
        - "-inkey"
        - "/dremio-tls-secret/tls.key"
        - "-in"
        - "/dremio-tls-secret/tls.crt"
        - "-out"
        - "/opt/dremio/tls/client.pkcs12"
        - "-passout"
        - "pass:"
      {{- end }}
      volumes:
      - name: dremio-master-log
        emptyDir: {}
      - name: log-script
        configMap:
          name: log-script
      - name: dremio-config
        configMap:
          name: dremio-config
      {{- if .Values.hive2 }}
      - name: dremio-hive2-config
        configMap:
          name: dremio-hive2-config
      {{- end }}
      {{- if .Values.hive3 }}
      - name: dremio-hive3-config
        configMap:
          name: dremio-hive3-config
      {{- end }}
      {{- if or .Values.tls.ui.enabled .Values.tls.client.enabled }}
      - name: dremio-tls
        emptyDir: {}
      {{- end }}
      {{- if .Values.tls.ui.enabled }}
      - name: dremio-tls-secret-ui
        secret:
          secretName: {{ .Values.tls.ui.secret }}
          items:
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
      {{- end }}
      {{- if .Values.tls.client.enabled }}
      - name: dremio-tls-secret-client
        secret:
          secretName: {{ .Values.tls.client.secret }}
          items:
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end}}
  volumeClaimTemplates:
  - metadata:
      name: dremio-master-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storageClass }}
      storageClassName: {{ .Values.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{.Values.coordinator.volumeSize}}
{{ end }}
