kind: Pod
apiVersion: v1
metadata:
  name: prometheus-exporter
spec:
  containers:
    - name: prometheus-exporter
      image: {{.Values.image}}:{{.Values.imageTag}}
      imagePullPolicy: Always
      volumeMounts:
      - name: config-vol
        mountPath: /app/config
  volumes:
  - name: config-vol
    configMap:
      name: appconfig
