kind: ConfigMap
apiVersion: v1
metadata:
  name: appconfig
data:
  config.cfg: |
      [DEFAULT]
      ACCOUNT={{ .Values.azure.account }}
      KEY={{ .Values.azure.key }}
      PROM={{ .Values.prometheus.promUILogin }}
      CONTAINER={{ .Values.prometheus.container }}
      URL={{ .Values.prometheus.url }}
